site_name: Jake Farrell
site_url: https://docs.jakefarrell.ie/
site_description: My Docs & Info

repo_name: CheeseLad/docs
repo_url: https://github.com/CheeseLad/docs

nav:
  - Welcome: index.md
  - Homelab:
    - Homelab Information: homelab/info.md
    - Service Information:
      - HedgeDoc: homelab/services/hedgedoc.md
      - Homepage: homelab/services/homepage.md
      - Pi-hole: homelab/services/pi-hole.md
      - Plex: homelab/services/plex.md
      - Portainer: homelab/services/portainer.md
      - Qbittorrent: homelab/services/qbittorrent.md
      - Radarr: homelab/services/radarr.md
      - Sonarr: homelab/services/sonarr.md
      - Tautulli: homelab/services/tautulli.md
      - Uptime Kuma: homelab/services/uptime-kuma.md
    - Devices: homelab/devices.md
  - VPS:
    - VPS Information: vps/info.md
    - Service Information:
      - Clubs & Socs API: vps/services/clubsandsocs-api.md
      - DCU Fotosoc Website: vps/services/dcufotosoc-website.md
      - DCU Media Production Society Website: vps/services/dcumps-website.md
      - MySQL Database: vps/services/mysql-database.md
      - Personal Website: vps/services/personal-website.md
      - Plausible Analytics: vps/services/plausible-analytics.md
      - Portainer: vps/services/portainer.md
      - Shlink URL Shortener: vps/services/shlink.md
  #- Redbrick: 
  #  - Redbrick Information: redbrick/redbrick.md
  #  - Email Generator: redbrick/email-generator.md
  #  - Secretary: redbrick/secretary.md
  #- MPS: 
  #  - MPS Information: mps/info.md
  #  - Website: mps/website.md
  - Projects: 
  #  - The Experiment: projects/the-experiment.md
    - Email System: projects/email-system.md
  #  - Personal Website: projects/personal-website.md
  #  - Roll On: projects/roll-on.md

theme:
  name: material
  font:
    text: Roboto
  logo: assets/avatar.png
  favicon: assets/avatar.png
  language: en 
  palette:
    - media: "(prefers-color-scheme: light)"
      scheme: default
      primary: deep orange
      toggle:
        icon: material/brightness-7 
        name: Switch to dark mode

    - media: "(prefers-color-scheme: dark)"
      scheme: slate
      primary: deep orange
      toggle:
        icon: material/brightness-4
        name: Switch to light mode
  features:
    - navigation.footer
    - navigation.tabs
    - navigation.top

plugins:
  - search
  - material-plausible

extra:
  social:
    - icon: fontawesome/solid/envelope
      link: mailto:jake_farrell@outlook.com
      name: Send me an email!
    - icon: fontawesome/brands/github
      link: https://github.com/CheeseLad
      name: Check out my GitHub!
    - icon: fontawesome/brands/linkedin
      link: https://www.linkedin.com/in/jake-farrell-2a4674239/
      name: Connect with me on LinkedIn!
    - icon: fontawesome/brands/instagram
      link: https://www.instagram.com/jakefarrell2003/
      name: Follow my Instagram!
  generator: false

  analytics:
    provider: plausible
    domain: docs.jakefarrell.ie
    src: "https://plausible.jakefarrell.ie/js/script.js"
