site_name: Jake Farrell
site_url: https://docs.jakefarrell.ie/
site_description: My Documentation

repo_name: CheeseLad/docs-jakefarrell
repo_url: https://github.com/CheeseLad/docs-jakefarrell

nav:
  - Home: index.md
  - Homelab:
    - Homelab Information: homelab/homelab.md
    - Services: homelab/services.md
    - Devices: homelab/devices.md
  - Redbrick: 
    - Redbrick Information: redbrick/redbrick.md
    - Email Generator: redbrick/email-generator.md
    - Secretary Handover: redbrick/secretary-handover.md
  - MPS: 
    - MPS Information: mps/mps.md
    - Website: mps/website.md
  - Projects: 
    - The Experiment: projects/the-experiment.md
theme:
  name: material
  font:
    text: Roboto
  logo: assets/avatar.png
  favicon: assets/avatar.png
  language: en 
  palette:
    - media: "(prefers-color-scheme: light)"
      scheme: default
      primary: deep orange
      toggle:
        icon: material/brightness-7 
        name: Switch to dark mode

    - media: "(prefers-color-scheme: dark)"
      scheme: slate
      primary: deep orange
      toggle:
        icon: material/brightness-4
        name: Switch to light mode
  features:
    - navigation.footer
    - navigation.tabs

plugins:
  - search
  - material-plausible

extra:
  social:
    - icon: fontawesome/solid/envelope
      link: mailto:jake_farrell@outlook.com
      name: Send me an email!
    - icon: fontawesome/brands/github
      link: https://github.com/CheeseLad
      name: Check out my GitHub!
    - icon: fontawesome/brands/linkedin
      link: https://www.linkedin.com/in/jake-farrell-2a4674239/
      name: Connect with me on LinkedIn!
    - icon: fontawesome/brands/instagram
      link: https://www.instagram.com/jakefarrell2003/
      name: Follow my Instagram!
  generator: false

  analytics:
    provider: plausible
    domain: docs.jakefarrell.ie
    src: "https://plausible.jakefarrell.ie/js/script.js"
